import { POEMapZone } from '@/models/PathOfExile';

/**
 * List of all hideouts from `poedb.tw/us/Hideouts`.
 *
 * Thanks MapWatch for this list (github.com/mapwatch/mapwatch).
 */
export const hideouts = [
  'Alpine Hideout',
  'Arboreal Hideout',
  'Backstreet Hideout',
  'Baleful Hideout',
  'Battle-scarred Hideout',
  'Brutal Hideout',
  "Cartographer's Hideout",
  'Celestial Hideout',
  "Champion's Hideout",
  'Coastal Hideout',
  'Coral Hideout',
  'Corrupted Hideout',
  'Desert Hideout',
  'Divided Hideout',
  'Doomguard Hideout',
  'Eclipsed Hideout',
  'Enlightened Hideout',
  'Excavated Hideout',
  'Furious Hideout',
  'Glacial Hideout',
  'Glimmerwood Hideout',
  'Haunted Hideout',
  'Immaculate Hideout',
  'Indomitable Hideout',
  'Innocent Hideout',
  'Lush Hideout',
  'Luxurious Hideout',
  'Morbid Hideout',
  'Overgrown Hideout',
  'Ravenous Hideout',
  "Robber's Trench Hideout",
  'Sanguine Hideout',
  'Shaped Hideout',
  'Skeletal Hideout',
  'Stately Hideout',
  'Sunken Hideout',
  'Sunspire Hideout',
  'Towering Hideout',
  'Undercity Hideout',
  'Unearthed Hideout'
];

/**
 * Extracted list of all regular maps from the Atlas (unique maps excluded).
 * This list needs to be updated every league when the Atlas changes.
 * It is directly extracted from the `ggpk` file of the game.
 *
 * Thanks MapWatch for this list (github.com/mapwatch/mapwatch).
 */
export const maps: POEMapZone[] = [
  { name: 'Sulphur Vents', tier: 1, unique: false },
  { name: 'Haunted Mansion', tier: 1, unique: false },
  { name: 'Desert', tier: 1, unique: false },
  { name: 'Ivory Temple', tier: 1, unique: false },
  { name: 'Glacier', tier: 2, unique: false },
  { name: 'Thicket', tier: 2, unique: false },
  { name: 'Alleyways', tier: 2, unique: false },
  { name: 'Lookout', tier: 2, unique: false },
  { name: 'Barrows', tier: 2, unique: false },
  { name: 'Armoury', tier: 2, unique: false },
  { name: 'Leyline', tier: 3, unique: false },
  { name: 'Mausoleum', tier: 3, unique: false },
  { name: 'Ashen Wood', tier: 3, unique: false },
  { name: 'Relic Chambers', tier: 3, unique: false },
  { name: 'Pier', tier: 3, unique: false },
  { name: 'Arid Lake', tier: 3, unique: false },
  { name: 'Arachnid Tomb', tier: 3, unique: false },
  { name: 'Flooded Mine', tier: 3, unique: false },
  { name: 'Wharf', tier: 3, unique: false },
  { name: 'Pen', tier: 3, unique: false },
  { name: 'Excavation', tier: 4, unique: false },
  { name: 'Crater', tier: 4, unique: false },
  { name: 'City Square', tier: 4, unique: false },
  { name: 'Fields', tier: 4, unique: false },
  { name: 'Cage', tier: 4, unique: false },
  { name: 'Grotto', tier: 4, unique: false },
  { name: 'Cursed Crypt', tier: 4, unique: false },
  { name: 'Strand', tier: 4, unique: false },
  { name: 'Channel', tier: 4, unique: false },
  { name: 'Beach', tier: 4, unique: false },
  { name: 'Marshes', tier: 5, unique: false },
  { name: 'Spider Lair', tier: 5, unique: false },
  { name: 'Tropical Island', tier: 5, unique: false },
  { name: 'Ramparts', tier: 5, unique: false },
  { name: 'Burial Chambers', tier: 5, unique: false },
  { name: 'Mesa', tier: 5, unique: false },
  { name: 'Jungle Valley', tier: 5, unique: false },
  { name: 'Peninsula', tier: 5, unique: false },
  { name: 'Arcade', tier: 5, unique: false },
  { name: 'Fungal Hollow', tier: 5, unique: false },
  { name: 'Mud Geyser', tier: 6, unique: false },
  { name: 'Courtyard', tier: 6, unique: false },
  { name: 'Ancient City', tier: 6, unique: false },
  { name: 'Atoll', tier: 6, unique: false },
  { name: 'Maze', tier: 6, unique: false },
  { name: 'Promenade', tier: 6, unique: false },
  { name: 'Cells', tier: 6, unique: false },
  { name: 'Phantasmagoria', tier: 6, unique: false },
  { name: 'Waste Pool', tier: 6, unique: false },
  { name: 'Overgrown Ruin', tier: 6, unique: false },
  { name: 'Primordial Pool', tier: 6, unique: false },
  { name: 'Residence', tier: 7, unique: false },
  { name: 'Spider Forest', tier: 7, unique: false },
  { name: 'Arena', tier: 7, unique: false },
  { name: 'Dungeon', tier: 7, unique: false },
  { name: 'Racecourse', tier: 7, unique: false },
  { name: 'Graveyard', tier: 7, unique: false },
  { name: 'Vault', tier: 7, unique: false },
  { name: 'Waterways', tier: 7, unique: false },
  { name: 'Conservatory', tier: 7, unique: false },
  { name: 'Laboratory', tier: 7, unique: false },
  { name: 'Overgrown Shrine', tier: 7, unique: false },
  { name: 'Iceberg', tier: 8, unique: false },
  { name: 'Pit', tier: 8, unique: false },
  { name: 'Ghetto', tier: 8, unique: false },
  { name: 'Bone Crypt', tier: 8, unique: false },
  { name: 'Chateau', tier: 8, unique: false },
  { name: 'Toxic Sewer', tier: 8, unique: false },
  { name: 'Scriptorium', tier: 8, unique: false },
  { name: 'Dunes', tier: 8, unique: false },
  { name: 'Factory', tier: 8, unique: false },
  { name: 'Necropolis', tier: 8, unique: false },
  { name: 'Estuary', tier: 8, unique: false },
  { name: 'Arachnid Nest', tier: 9, unique: false },
  { name: 'Port', tier: 9, unique: false },
  { name: 'Villa', tier: 9, unique: false },
  { name: 'Mineral Pools', tier: 9, unique: false },
  { name: 'Underground River', tier: 9, unique: false },
  { name: 'Underground Sea', tier: 9, unique: false },
  { name: 'Castle Ruins', tier: 9, unique: false },
  { name: 'Shore', tier: 9, unique: false },
  { name: 'Moon Temple', tier: 9, unique: false },
  { name: 'Arsenal', tier: 9, unique: false },
  { name: 'Lighthouse', tier: 9, unique: false },
  { name: 'Sepulchre', tier: 10, unique: false },
  { name: 'Coral Ruins', tier: 10, unique: false },
  { name: 'Volcano', tier: 10, unique: false },
  { name: 'Geode', tier: 10, unique: false },
  { name: 'Bog', tier: 10, unique: false },
  { name: 'Plateau', tier: 10, unique: false },
  { name: 'Lava Chamber', tier: 10, unique: false },
  { name: 'Bazaar', tier: 10, unique: false },
  { name: 'Academy', tier: 10, unique: false },
  { name: 'Temple', tier: 10, unique: false },
  { name: 'Infested Valley', tier: 11, unique: false },
  { name: 'Dig', tier: 11, unique: false },
  { name: 'Lair', tier: 11, unique: false },
  { name: 'Malformation', tier: 11, unique: false },
  { name: 'Siege', tier: 11, unique: false },
  { name: 'Gardens', tier: 11, unique: false },
  { name: 'Crimson Temple', tier: 11, unique: false },
  { name: 'Precinct', tier: 11, unique: false },
  { name: 'Colonnade', tier: 11, unique: false },
  { name: 'Museum', tier: 11, unique: false },
  { name: 'Lava Lake', tier: 12, unique: false },
  { name: 'Cemetery', tier: 12, unique: false },
  { name: 'Vaal Pyramid', tier: 12, unique: false },
  { name: 'Park', tier: 12, unique: false },
  { name: 'Shipyard', tier: 12, unique: false },
  { name: 'Core', tier: 12, unique: false },
  { name: 'Carcass', tier: 12, unique: false },
  { name: 'Canyon', tier: 12, unique: false },
  { name: 'Colosseum', tier: 12, unique: false },
  { name: 'Tower', tier: 13, unique: false },
  { name: 'Sunken City', tier: 13, unique: false },
  { name: 'Defiled Cathedral', tier: 13, unique: false },
  { name: 'Belfry', tier: 13, unique: false },
  { name: 'Coves', tier: 13, unique: false },
  { name: 'Shrine', tier: 13, unique: false },
  { name: 'Plaza', tier: 13, unique: false },
  { name: 'Terrace', tier: 13, unique: false },
  { name: 'Reef', tier: 13, unique: false },
  { name: 'Primordial Blocks', tier: 14, unique: false },
  { name: 'Orchard', tier: 14, unique: false },
  { name: 'Wasteland', tier: 14, unique: false },
  { name: 'Crystal Ore', tier: 14, unique: false },
  { name: 'Courthouse', tier: 14, unique: false },
  { name: 'Basilica', tier: 14, unique: false },
  { name: 'Dark Forest', tier: 14, unique: false },
  { name: 'Summit', tier: 15, unique: false },
  { name: 'Caldera', tier: 15, unique: false },
  { name: 'Acid Caverns', tier: 15, unique: false },
  { name: 'Desert Spring', tier: 15, unique: false },
  { name: 'Palace', tier: 15, unique: false },
  { name: 'Vaal Temple', tier: 16, unique: false },
  { name: 'Forge of the Phoenix', tier: 16, unique: false },
  { name: 'Maze of the Minotaur', tier: 16, unique: false },
  { name: 'Pit of the Chimera', tier: 16, unique: false },
  { name: 'Lair of the Hydra', tier: 16, unique: false }
];

/**
 * Extracted list of all unique maps from the Atlas.
 * This list needs to be updated every league when the Atlas changes.
 * It is directly extracted from the `ggpk` file of the game.
 *
 * Thanks MapWatch for this list (github.com/mapwatch/mapwatch).
 */
export const uniqueMaps: POEMapZone[] = [
  { name: 'Whakawairua Tuahu', tier: 4, unique: true },
  { name: "The Coward's Trial", tier: 4, unique: true },
  { name: 'Untainted Paradise', tier: 5, unique: true },
  { name: 'Hall of Grandmasters', tier: 6, unique: true },
  { name: 'Maelström of Chaos', tier: 6, unique: true },
  { name: 'The Vinktar Square', tier: 6, unique: true },
  { name: "Doryani's Machinarium", tier: 6, unique: true },
  { name: "Acton's Nightmare", tier: 7, unique: true },
  { name: "Olmec's Sanctum", tier: 8, unique: true },
  { name: 'Perandus Manor', tier: 8, unique: true },
  { name: 'Pillars of Arun', tier: 8, unique: true },
  { name: 'Death and Taxes', tier: 8, unique: true },
  { name: 'Mao Kun', tier: 9, unique: true },
  { name: 'The Twilight Temple', tier: 9, unique: true },
  { name: "Caer Blaidd, Wolfpack's Den", tier: 9, unique: true },
  { name: "Oba's Cursed Trove", tier: 9, unique: true },
  { name: "Poorjoy's Asylum", tier: 10, unique: true },
  { name: 'The Putrid Cloister', tier: 11, unique: true },
  { name: 'Hallowed Ground', tier: 12, unique: true },
  { name: 'Vaults of Atziri', tier: 12, unique: true }
];

/**
 * Sometimes the name of the map is not exactly the one used in the URL. We can
 * retrieve all the maps URL from `poedb.tw/us/area.php?cn=Map`.
 *
 * Thanks MapWatch for this list (github.com/mapwatch/mapwatch).
 */
export const rawMapsImageURL = [
  { name: 'Lookout', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Lookout.png' },
  { name: 'Beach', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Beach.png' },
  { name: 'Graveyard', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Graveyard.png' },
  { name: 'Dungeon', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Dungeon.png' },
  { name: 'Alleyways', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Alleyways.png' },
  { name: 'Pen', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Pen.png' },
  { name: 'Desert', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Desert.png' },
  { name: 'Arid Lake', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/AridLake.png' },
  { name: 'Flooded Mine', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Cavern.png' },
  { name: 'Marshes', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Marshes.png' },
  { name: 'Iceberg', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Iceberg.png' },
  { name: 'Cage', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Cage.png' },
  { name: 'Fungal Hollow', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/FungalCaverns.png' },
  { name: 'Excavation', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Excavation.png' },
  { name: 'Leyline', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/SulphurWastes.png' },
  { name: 'Peninsula', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/DryPeninsula.png' },
  { name: 'Port', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Quay.png' },
  { name: 'Burial Chambers', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/BurialChambers.png' },
  { name: 'Cells', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Cells.png' },
  { name: 'Arcade', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Arcade.png' },
  { name: 'City Square', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/CitySquare.png' },
  { name: 'Relic Chambers', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Antiquary.png' },
  { name: 'Courthouse', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Courthouse.png' },
  { name: 'Strand', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Strand.png' },
  { name: 'Whakawairua Tuahu', url: '//web.poecdn.com/image/Art/2DItems/Maps/UniqueMapEye.png' },
  { name: 'Chateau', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Chateau.png' },
  { name: 'Grotto', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Grotto.png' },
  { name: 'Glacier', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Glacier.png' },
  { name: 'Volcano', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Volcano.png' },
  { name: 'Lighthouse', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Beacon.png' },
  { name: 'Canyon', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Canyon.png' },
  { name: 'Conservatory', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Baths.png' },
  { name: 'Sulphur Vents', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Corrosion.png' },
  { name: 'Haunted Mansion', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Chambers.png' },
  { name: 'Maze', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Maze.png' },
  { name: 'Channel', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Channel.png' },
  { name: 'Toxic Sewer', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Sewer.png' },
  { name: 'Ancient City', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/VaalCity.png' },
  { name: 'Ivory Temple', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/IvoryTemple.png' },
  { name: 'Spider Lair', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/SpiderLair.png' },
  { name: 'Barrows', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Barrows.png' },
  { name: 'Mausoleum', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Mausoleum.png' },
  { name: 'Fields', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Fields.png' },
  { name: 'Jungle Valley', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/JungleValley.png' },
  { name: 'Phantasmagoria', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Phantasmagoria.png' },
  { name: 'Academy', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Academy.png' },
  { name: 'Thicket', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Thicket.png' },
  { name: 'Wharf', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Wharf.png' },
  { name: 'Ashen Wood', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/DryWoods.png' },
  { name: 'Atoll', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Atoll.png' },
  { name: 'Maelström of Chaos', url: '//web.poecdn.com/image/Art/2DItems/Maps/MaelstromofChaos.png' },
  { name: 'Cemetery', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Cemetery.png' },
  { name: 'Underground Sea', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/UndergroundSea.png' },
  { name: 'Crater', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Tribunal.png' },
  { name: 'Coral Ruins', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/CorpseTrench.png' },
  { name: 'Lava Chamber', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Crematorium.png' },
  { name: 'Residence', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Residence.png' },
  { name: 'Ramparts', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Ramparts.png' },
  { name: 'Dunes', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Dunes.png' },
  { name: 'Pillars of Arun', url: '//web.poecdn.com/image/Art/2DItems/Maps/PillarsOfVastiri.png' },
  { name: 'Bone Crypt', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Catacomb.png' },
  { name: 'Underground River', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/UndergroundRiver.png' },
  { name: "Caer Blaidd, Wolfpack's Den", url: '//web.poecdn.com/image/Art/2DItems/Maps/WolfMap.png' },
  { name: 'Gardens', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Terrace.png' },
  { name: 'Arachnid Nest', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/ArachnidNest.png' },
  { name: 'Bazaar', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Bazaar.png' },
  { name: 'Laboratory', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Laboratory.png' },
  { name: 'Infested Valley', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Infestation.png' },
  { name: 'Overgrown Ruin', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/OvergrownRuin.png' },
  { name: 'Vaal Pyramid', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/VaalPyramid.png' },
  { name: 'Vaults of Atziri', url: '//web.poecdn.com/image/Art/2DItems/Maps/UniqueMap1.png' },
  { name: 'Geode', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Quarry.png' },
  { name: 'Armoury', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Armory.png' },
  { name: 'Courtyard', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Courtyard.png' },
  { name: 'The Vinktar Square', url: '//web.poecdn.com/image/Art/2DItems/Maps/TheVinktarSquare.png' },
  { name: 'Mud Geyser', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/MudGeyser.png' },
  { name: 'Shore', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Shore.png' },
  { name: 'Tropical Island', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/TropicalIsland.png' },
  { name: 'Mineral Pools', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/MineralPools.png' },
  { name: 'Moon Temple', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/LunarisTemple.png' },
  { name: 'The Twilight Temple', url: '//web.poecdn.com/image/Art/2DItems/Maps/Celestial.png' },
  { name: 'Sepulchre', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Sepulchre.png' },
  { name: 'Tower', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Tower.png' },
  { name: 'Waste Pool', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/WastePool.png' },
  { name: 'Plateau', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Plateau.png' },
  { name: 'Estuary', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Estuary.png' },
  { name: 'Vault', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Vault.png' },
  { name: 'Temple', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Temple.png' },
  { name: "Poorjoy's Asylum", url: '//web.poecdn.com/image/Art/2DItems/Maps/PoorjoysAsylum.png' },
  { name: 'Arena', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Arena.png' },
  { name: 'Museum', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Museum.png' },
  { name: 'The Putrid Cloister', url: '//web.poecdn.com/image/Art/2DItems/Maps/PutridCloister.png' },
  { name: 'Scriptorium', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Scriptorium.png' },
  { name: 'Siege', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Boulevard.png' },
  { name: 'Shipyard', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Shipyard.png' },
  { name: 'Belfry', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Belfry.png' },
  { name: 'Arachnid Tomb', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Arachnid.png' },
  { name: 'Wasteland', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Wasteland.png' },
  { name: 'Precinct', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Precinct.png' },
  { name: 'Bog', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Bog.png' },
  { name: 'Pier', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Pier.png' },
  { name: 'Cursed Crypt', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Crypt.png' },
  { name: 'Orchard', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Orchard.png' },
  { name: 'Promenade', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Promenade.png' },
  { name: 'Hall of Grandmasters', url: '//web.poecdn.com/image/Art/2DItems/Maps/HallOfGrandmasters.png' },
  { name: 'Lair', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Lair.png' },
  { name: 'Colonnade', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Colonnade.png' },
  { name: 'Primordial Pool', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/PrimordialPool.png' },
  { name: 'Spider Forest', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/SpiderForest.png' },
  { name: 'Coves', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Coves.png' },
  { name: 'Waterways', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Waterways.png' },
  { name: 'Factory', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Factory.png' },
  { name: 'Mesa', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Mesa.png' },
  { name: 'Pit', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Pit1.png' },
  { name: 'Defiled Cathedral', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/DefiledCathedral.png' },
  { name: 'Summit', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Summit.png' },
  { name: 'Overgrown Shrine', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/OvergrownShrine.png' },
  { name: "Acton's Nightmare", url: '//web.poecdn.com/image/Art/2DItems/Maps/musicbox.png' },
  { name: 'Castle Ruins', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/CastleRuins.png' },
  { name: 'Crystal Ore', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/CrystalOre.png' },
  { name: 'Villa', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Villa.png' },
  { name: 'Primordial Blocks', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/PrimevalRuins.png' },
  { name: "Oba's Cursed Trove", url: '//web.poecdn.com/image/Art/2DItems/Maps/oba.png' },
  { name: 'Necropolis', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Necropolis.png' },
  { name: 'Death and Taxes', url: '//web.poecdn.com/image/Art/2DItems/Maps/DeathandTaxes.png' },
  { name: 'Racecourse', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Racecourse.png' },
  { name: 'Caldera', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Abyss.png' },
  { name: 'Ghetto', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Ghetto.png' },
  { name: 'Park', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Park.png' },
  { name: 'Malformation', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Malformation.png' },
  { name: 'Terrace', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/HighGardens.png' },
  { name: 'Shrine', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Shrine.png' },
  { name: 'Arsenal', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Arsenal.png' },
  { name: 'Desert Spring', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Oasis.png' },
  { name: 'Core', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Core.png' },
  { name: 'Colosseum', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Colosseum.png' },
  { name: 'Acid Caverns', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/SulphurVents.png' },
  { name: 'Dark Forest', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/DarkForest.png' },
  { name: 'Crimson Temple', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Sanctuary.png' },
  { name: 'Plaza', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Plaza.png' },
  { name: 'Dig', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Dig.png' },
  { name: 'Palace', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Palace.png' },
  { name: 'Lava Lake', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Corpse.png' },
  { name: 'Basilica', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Basilica.png' },
  { name: 'Sunken City', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/SunkenCity.png' },
  { name: 'Reef', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Reef.png' },
  { name: 'Carcass', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Carcass.png' },
  { name: 'Pit of the Chimera', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Chimera.png' },
  { name: 'Lair of the Hydra', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Hydra.png' },
  { name: 'Maze of the Minotaur', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Minotaur.png' },
  { name: 'Forge of the Phoenix', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Phoenix.png' },
  { name: 'Vaal Temple', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/VaalTempleBase.png' },
  { name: 'Arachnid Tomb', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Arachnid.png' },
  { name: 'Lava Lake', url: '//web.poecdn.com/image/Art/2DItems/Maps/Atlas2Maps/New/Corpse.png' }
];
